/****** Script for SelectTopNRows command from SSMS  ******/
SELECT
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[PhoneNumber]
      ,[PhoneNumberType]
      ,[EmailAddress]
      ,[EmailPromotion]
      ,[AddressType]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[City]
      ,[StateProvinceName]
      ,[PostalCode]
      ,[CountryRegionName]
      ,[Demographics]
  FROM [AdventureWorks2016_EXT].[Sales].[vIndividualCustomer]